{
    "swagger": "2.0",
    "info": {
        "version": "0.0.0",
        "title": "Notification Worker"
    },
    "paths": {
        "/DynamicClientLeft": {
            "get": {
                "description": "Differences are in these tags-\n\n\"CommandType\":\"DynamicClientLeft\"\n\n\"Action\":\"update\"\n",
                "parameters": [
                    {
                        "name": "payload",
                        "in": "body",
                        "description": "What a default Payload would look like",
                        "schema": {
                            "$ref": "#/definitions/WifiPayload"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert would be of type - \"client_name\" \"manufacturer\" rejoined \"Al_Name\"",
                        "schema": {
                            "$ref": "#/definitions/GCMWifi"
                        }
                    }
                }
            }
        },
        "/DynamicClientJoined": {
            "get": {
                "description": "Differences are in these tags-\n\n\"CommandType\":\"DynamicClientJoined\"\n\n\"Action\":\"update\"\n",
                "parameters": [
                    {
                        "name": "payload",
                        "in": "body",
                        "description": "What a default Payload would look like",
                        "schema": {
                            "$ref": "#/definitions/WifiPayload"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert would be of type - \"client_name\" \"manufacturer\" just Left \"Al_Name\"",
                        "schema": {
                            "$ref": "#/definitions/GCMWifi"
                        }
                    }
                }
            }
        },
        "/DynamicClientAdded": {
            "get": {
                "description": "Differences are in these tags-\n\n\"CommandType\":\"DynamicClientAdded\"\n\n\"Action\":\"add\"\n",
                "parameters": [
                    {
                        "name": "payload",
                        "in": "body",
                        "description": "What a default Payload would look like",
                        "schema": {
                            "$ref": "#/definitions/WifiPayload"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert would be of type -  An unknown device \"Manufacturer_Name\" just joined \"Al_Name\"",
                        "schema": {
                            "$ref": "#/definitions/GCMWifi"
                        }
                    }
                }
            }
        },
        "/DynamicClientRemoved": {
            "get": {
                "description": "Differences are in these tags-\n\n\"CommandType\":\"DynamicClientRemoved\"\n\n\"Action\":\"remove\"\n",
                "parameters": [
                    {
                        "name": "payload",
                        "in": "body",
                        "description": "What a default Payload would look like",
                        "schema": {
                            "$ref": "#/definitions/WifiPayload"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert would be of type -  \"Al_Name\"'s \"client_name\" is reset",
                        "schema": {
                            "$ref": "#/definitions/GCMWifi"
                        }
                    }
                }
            }
        },
        "/DynamicIndexUpdated": {
            "get": {
                "description": "Differences are in these tags-\n\n\"CommandType\":\"DynamicIndexUpdated\"\n\n\"Action\":\"UpdateIndex\"\n",
                "parameters": [
                    {
                        "name": "payload",
                        "in": "body",
                        "description": "What a default Payload would look like",
                        "schema": {
                            "$ref": "#/definitions/DevicePayload"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert would depend on the device type and the operation performed by it",
                        "schema": {
                            "$ref": "#/definitions/GCM"
                        }
                    }
                }
            }
        },
        "/DirectPass": {
            "get": {
                "description": "Is passed as is, the alert is also given by the Cloud and not stored in any databases",
                "parameters": [
                    {
                        "name": "payload",
                        "in": "body",
                        "description": "What a default Payload would look like",
                        "schema": {
                            "$ref": "#/definitions/directPass"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Alert would depend on the device type and the operation performed by it",
                        "schema": {
                            "$ref": "#/definitions/directPassGCM"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "GCM": {
            "type": "object",
            "properties": {
                "mac": {
                    "type": "string"
                },
                "badge": {
                    "type": "integer"
                },
                "users": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "index": {
                    "type": "string"
                },
                "indexname": {
                    "type": "string"
                },
                "indexValue": {
                    "type": "string"
                },
                "devicetype": {
                    "type": "string"
                },
                "devicename": {
                    "type": "string"
                },
                "alert": {
                    "type": "string"
                },
                "registration_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "example": {
              "mac": "251175433168140",
              "badge":1,
              "users":"522225988",
              "time":"1484743183000",
              "index":"1",
              "indexValue":"true",
              "Devicetype":"64",
              "devicename":"My LED",
              "alert":"My LED is turned On",
              "registration_ids":["APA91bG4MPBaOIiU2GdXWEiARhru-T8qIQqmLUZT1vgJwcSI5mU5ngCeJxRkLYyMHkI00pK0rFmFALInYR4G_URwmX7oAIxMxhP3wPzyW0t1rRx0EBjMmVqESxsxvzVZopaQZQFY4kHVEensSrohYfvSzJGjZK3iX5Ud02LjafmTjTHMeibOytY", "APA91bGlJNJd3XGIdVDwdcqpRmXJOBQhYvYqLoZw9jeEKpwP4EW959CP6hL4e27QLYfKKrYZ95WKsc4GfOmSeDn2MUTG8GcereG6JveqlhwrAHMOfv5B_D9jnLQHn9mCQDqQqE7mXnAo6__d0ABXb3kEnDVgpbMzgoyXGvedxWe7gxR7YNCI4BQ"]
            }
        },
        "directPassGCM": {
            "type": "object",
            "properties": {
                "mac": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "users": {
                    "type": "string"
                },
                "NotiType": {
                    "type": "string"
                },
                "alert": {
                    "type": "string"
                },
                "registration_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "example": {
              "users":"522225988",
              "mac": "251175433168140",
              "time":"1484743183000",
              "NotiType":"DirectPass",
              "alert":"Whatever alert you want to send directly and not have saved in any cassandra database",

                
                
                
                
                "registration_ids":["APA91bG4MPBaOIiU2GdXWEiARhru-T8qIQqmLUZT1vgJwcSI5mU5ngCeJxRkLYyMHkI00pK0rFmFALInYR4G_URwmX7oAIxMxhP3wPzyW0t1rRx0EBjMmVqESxsxvzVZopaQZQFY4kHVEensSrohYfvSzJGjZK3iX5Ud02LjafmTjTHMeibOytY", "APA91bGlJNJd3XGIdVDwdcqpRmXJOBQhYvYqLoZw9jeEKpwP4EW959CP6hL4e27QLYfKKrYZ95WKsc4GfOmSeDn2MUTG8GcereG6JveqlhwrAHMOfv5B_D9jnLQHn9mCQDqQqE7mXnAo6__d0ABXb3kEnDVgpbMzgoyXGvedxWe7gxR7YNCI4BQ"]
            }
        },
        "DevicePayload": {
            "type": "object",
            "properties": {
                "mac": {
                    "type": "string"
                },
                "user_list": {
                    "type": "string"
                },
                "UTCTime": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/innerData"
                }
            },
            "example": {
              "mac": "251175433168140",
              "user_list": "522225988",
              "UTCTime": "1484743183000",
              "data": {
                "CommandType":"DynamicIndexUpdated",
                "Action":"UpdateIndex",
                "HashNow":"5faf3a031d39781cd5d7e77a3522bb49"
              }
            }
        },
        "directPass": {
            "type": "object",
            "properties": {
                "mac": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "users": {
                    "type": "string"
                },
                "NotiType": {
                    "type": "string"
                },
                "alert": {
                    "type": "string"
                }
            },
            "example": {
              "mac":"251175433168140",
              "time":"1484743183000",
              "users":"522225988",
              "NotiType":"DirectPass",
              "alert":"Whatever alert you want to send directly and not have saved in any cassandra database"
            }
        },
        "innerData": {
            "type": "object",
            "properties": {
                "CommandType": {
                    "type": "string"
                },
                "Action": {
                    "type": "string"
                },
                "HashNow": {
                    "type": "string"
                },
                "Devices": {
                    "$ref": "#/definitions/innerDevices"
                }
            },
            "example": {
              "CommandType":"DynamicIndexUpdated",
              "Action":"UpdateIndex",
              "HashNow":"5faf3a031d39781cd5d7e77a3522bb49"
            }
          },
        "innerDevices": {
            "type": "object",
            "properties": {
                "DeviceValues": {
                    "type": "object",
                    "properties": {
                        "IndexID": {
                            "$ref": "#/definitions/innerIndexID"
                        }
                    }
                }
            }
        },
        "innerIndexID": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Value": {
                    "type": "string"
                }
            },
            "example":{
              "Name":"SWITCH BINARY",
              "Value":"true"
              }
        },
        "WifiPayload": {
            "type": "object",
            "properties": {
                "mac": {
                    "type": "string"
                },
                "user_list": {
                    "type": "string"
                },
                "UTCTime": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/innerItem"
                },
                "wifiClients": {
                    "type": "string"
                },
                "dbRows": {
                    "$ref": "#/definitions/innerdbRows"
                }
            },
            "example":{
              "mac":"251175433168140",
              "user_list":"522225988",
              "UTCTime":"1484743183000",
              "wifiClients":"true",
              }
        },
        "innerItem": {
            "type": "object",
            "properties": {
                "CommandType": {
                    "type": "string"
                },
                "Action": {
                    "type": "string"
                },
                "Clients": {
                    "$ref": "#/definitions/innerClient"
                },
                "HashNow": {
                    "type": "string"
                }
            },
            "example":{
              "CommandType":"DynamicClientRemoved",
              "Action":"remove",
              "HashNow":"759b96aee60cd590a341d733ed9a3a26"
              }
        },
        "innerClient": {
            "type": "object",
            "properties": {
                "ClientID": {
                    "$ref": "#/definitions/innerClientID"
                }
            }
        },
        "GCMWifi": {
            "type": "object",
            "properties": {
                "badge": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                },
                "alert": {
                    "type": "string"
                },
                "users": {
                    "type": "string"
                },
                "NotiType": {
                    "type": "string"
                },
                "mac": {
                    "type": "string"
                },
                "registration_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "example":{
              "badge":209,
              "time":"1484743183000",
              "alert":"My zenfone 5 (ASUSTek ) just Left ALMOND +",
              "users":"522256983",
              "NotiType":"wifiClients",
              "mac":"251175433168140",
              "registration_ids":["APA91bG4MPBaOIiU2GdXWEiARhru-T8qIQqmLUZT1vgJwcSI5mU5ngCeJxRkLYyMHkI00pK0rFmFALInYR4G_URwmX7oAIxMxhP3wPzyW0t1rRx0EBjMmVqESxsxvzVZopaQZQFY4kHVEensSrohYfvSzJGjZK3iX5Ud02LjafmTjTHMeibOytY", "APA91bGlJNJd3XGIdVDwdcqpRmXJOBQhYvYqLoZw9jeEKpwP4EW959CP6hL4e27QLYfKKrYZ95WKsc4GfOmSeDn2MUTG8GcereG6JveqlhwrAHMOfv5B_D9jnLQHn9mCQDqQqE7mXnAo6__d0ABXb3kEnDVgpbMzgoyXGvedxWe7gxR7YNCI4BQ"]
              }
        },
        "innerClientID": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Connection": {
                    "type": "string"
                },
                "MAC": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                },
                "LastKnownIP": {
                    "type": "string"
                },
                "Active": {
                    "type": "string"
                },
                "UseAsPresence": {
                    "type": "string"
                },
                "LastActiveEpoch": {
                    "type": "string"
                },
                "Wait": {
                    "type": "string"
                },
                "Block": {
                    "type": "string"
                },
                "Schedule": {
                    "type": "string"
                },
                "Manufacturer": {
                    "type": "string"
                },
                "RSSI": {
                    "type": "string"
                },
                "ForceInActive": {
                    "type": "string"
                },
                "CanBlock": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                }
            },
            "example":{
              "Name":"MI4W-MiPhone",
              "Connection":"wireless",
              "MAC":"74:51:ba:d2:37:e0",
              "Type":"other",
              "LastKnownIP":"10.10.10.183",
              "Active":"true",
              "UseAsPresnce":"true",
              "LastActiveEpoch":"1477906264",
              "Wait":"6",
              "Block":"0",
              "Schedule":"0,0,0,0,0,0,0",
              "Manufacturer":"Xiaomi",
              "RSSI":"-66",
              "ForceInActive":"0",
              "CanBlock":"true",
              "Category":"Others"
              }
        },
        "innerdbRows": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Connection": {
                    "type": "string"
                },
                "MAC": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                },
                "LastKnownIP": {
                    "type": "string"
                },
                "Active": {
                    "type": "string"
                },
                "UseAsPresnce": {
                    "type": "string"
                },
                "LastActiveEpoch": {
                    "type": "string"
                },
                "Wait": {
                    "type": "string"
                },
                "Block": {
                    "type": "string"
                },
                "Schedule": {
                    "type": "string"
                },
                "Manufacturer": {
                    "type": "string"
                },
                "RSSI": {
                    "type": "string"
                },
                "ForceInActive": {
                    "type": "string"
                },
                "CanBlock": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                },
                "ID": {
                    "type": "string"
                }
            },
            "example":{
              "Name":"MI4W-MiPhone",
              "Connection":"wireless",
               "MAC":"74:51:ba:d2:37:e0",
              "Type":"other",
              "LastKnownIP":"10.10.10.183",
              "Active":"true",
              "UseAsPresence":"true",
              "LastActiveEpoch":"1477906264",
              "Wait":"6",
              "Block":"0",
              "Schedule":"0,0,0,0,0,0,0",
              "Manufacturer":"Xiaomi ",
              "RSSI":"-66",
              "ForceInActive":"0",
              "CanBlock":"true",
              "Category":"Others",
              "ID":"28"
              }
        }
    }
